name = "Nupack"
author = "Deveyus"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a7e384a18d4d10fb64b3a28dc33a460db6b9c03f41007cfdb9d2fcc49ce807a"

[versions]
forge = "47.3.10"
minecraft = "1.20.1"
