# First stage: Build packwiz from source
FROM golang:alpine AS builder

# Install necessary packages
RUN apk update && apk add --no-cache git

# Build packwiz from source
RUN go install github.com/packwiz/packwiz@latest

# Use the official Alpine image as a base
FROM alpine:latest

# Install necessary packages
RUN apk update && \
    apk add --no-cache \
    build-base \
    curl \
    git \
    openssl \
    openssl-dev \
    zsh

# Install Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Set theme to agnoster
RUN sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/g' ~/.zshrc

# Install zsh-syntax-highlighting plugin
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
RUN sed -i 's/plugins=(git)/plugins=(git zsh-syntax-highlighting)/g' ~/.zshrc

# Set default shell to zsh
ENV SHELL /bin/zsh

# Set custom prompt without hostname
RUN echo 'PROMPT="[%F{cyan}%n%f | %F{green}%~%f] "' >> /root/.zshrc

# Copy the packwiz binary from the builder stage
COPY --from=builder /go/bin/packwiz /usr/local/bin/packwiz

# Ensure /usr/local/bin is in the PATH
ENV PATH="/usr/local/bin:${PATH}"